service: cart-service

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}

plugins:
  - serverless-offline
  - serverless-stage-manager

functions:
  main:
    handler: dist/main.handler
    events:
      - http: 
          method: ANY 
          path: /
      - http: 
          method: ANY 
          path: /{proxy+}

custom:
  stages:
   - dev
   - prod